def sum(self):
 return self.value1+self.value2
def diff(self):
    return self.value1-self.value2
def mul(self):
     return self.value1*self.value2
def div(self):
    return self.value1/self.value2
def mod(self):
    return self.value1%self.value2