from tkinter import *
w=Tk()
w.title("sample")
w.configure(bg="black")
w.geometry("600x400")
l=Label(text="Enter numbers ",fg="red",bg="black")
l.pack()
l.place(y=20,x=180)
e=Entry()
e.pack()
e.place(y=20,x=270)
f=Entry()
f.pack()
f.place(y=20,x=400)
def dis():
    lb=Label(text=int(e.get())+int(f.get()))
    lb.pack()
    lb.place(y=95,x=270)
p=Button(text="+",bg="black",fg="red",width=5,command=dis)
p.pack()
p.place(y=50,x=270)
def fis():
    lb=Label(text=int(e.get())-int(f.get()))
    lb.pack()
    lb.place(y=95,x=270)
q=Button(text="-",bg="black",fg="red",width=5,command=fis)
q.pack()
q.place(y=50,x=320)
def kis():
    lb=Label(text=int(e.get())*int(f.get()))
    lb.pack()
    lb.place(y=95,x=270)
r=Button(text="*",bg="black",fg="red",width=5,command=kis)
r.pack()
r.place(y=50,x=370)
def mis():
    lb=Label(text=int(e.get())/int(f.get()))
    lb.pack()
    lb.place(y=95,x=270)
s=Button(text="/",bg="black",fg="red",width=5,command=mis)
s.pack()
s.place(y=50,x=420)
w.mainloop()
